### ISSUE TITLE
SiteOrigin Widgets Bundle Error

### ISSUE THREAD

**Issue by aldrin-does-code** [iGovPhil/gwt-wordpress#62]
Hi. As stated SiteOrigin Widgets Bundle is one of the GWHS-approved plugins. However, this plugin throws me this error in the block editor: "This block has encountered an error and cannot be previewed."

Upon further checking, this points me to this fatal error:

`Fatal error: Uncaught Error: Call to undefined function wp_should_skip_block_supports_serialization() in C:\xampp\htdocs\sph\wp-includes\block-supports\elements.php:107 Stack trace: #0 C:\xampp\htdocs\sph\wp-includes\class-wp-hook.php(310): wp_render_elements_support_styles(NULL, Array) #1 C:\xampp\htdocs\sph\wp-includes\plugin.php(205): WP_Hook->apply_filters(NULL, Array) #2 C:\xampp\htdocs\sph\wp-includes\blocks.php(1004): apply_filters('pre_render_bloc...', NULL, Array, NULL) #3 C:\xampp\htdocs\sph\wp-includes\blocks.php(1089): render_block(Array) #4 C:\xampp\htdocs\sph\wp-includes\class-wp-hook.php(308): do_blocks('make_clickable') #5 C:\xampp\htdocs\sph\wp-includes\plugin.php(205): WP_Hook->apply_filters('make_clickable', Array) #6 C:\xampp\htdocs\sph\wp-content\themes\gwt-wordpress-25.3.3\inc\function-initialize.php(91): apply_filters('the_content', 'make_clickable') #7 C:\xampp\htdocs\sph\wp-includes\class-wp-hook.php(308): gwt_wp_setup('') #8 C:\xampp\htdocs\sph\wp-includes\class-wp-hook.php(332): WP_Hook->apply_f in C:\xampp\htdocs\sph\wp-includes\block-supports\elements.php on line 107`

The current version for WordPress I am using is 6.1.1. For XAMPP is x64-7.4.30-1-VC15. The theme I am also using is the 25.3.3.

What should I do to resolve this? Thank you

**Comment by lamerock** [comment]
I believe this error is not related to the GWT template.

Anyway, try to re-install the Wordpress Installation via Wordpress Admin Dashboard.
If you still getting the error after re-installing, try to disable each plugins you installed and see if the error still appears.
It is possible that there is a conflict of plugins especially if you installed the Classic Editor plugin.
If it did not work, you may contact the developers of SiteOrigin WIdgets Bundle, either at their wordpress.org page or at their Github Repo. Hope this helps.

**Comment by aldrin-does-code** [comment]
Copy this. Thank you!
