### ISSUE TITLE
How to fix this issue Fatal Error in Theme Options

### ISSUE THREAD

**Issue by itszaheerlgs** [iGovPhil/gwt-wordpress#69]
Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method GOVPH::govph_options_page() cannot be called statically in C:\xampp2\htdocs\dict\wp-includes\class-wp-hook.php:308 Stack trace: #0 C:\xampp2\htdocs\dict\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #1 C:\xampp2\htdocs\dict\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #2 C:\xampp2\htdocs\dict\wp-admin\admin.php(259): do_action('appearance_page...') #3 C:\xampp2\htdocs\dict\wp-admin\themes.php(10): require_once('C:\\xampp2\\htdoc...') #4 {main} thrown in C:\xampp2\htdocs\dict\wp-includes\class-wp-hook.php on line 308

**Comment by gumacahin** [comment]
Try defining`GOVPH::govph_options_page()` as a static method by adding the static keyword to the function definition.

This theme was developed back when PHP allowed non-static method to be called in a non-static context. You'll need to updated a number of  methods that are non-static but are being called in a static context.

**Comment by itszaheerlgs** [comment]
> Try defining`GOVPH::govph_options_page()` as a static method by adding the static keyword to the function definition.
> 
> This theme was developed back when PHP allowed non-static method to be called in a non-static context. You'll need to updated a number a number of methods that are non-static but are being called in a static context.

what php file should I need to update.

**Comment by gumacahin** [comment]
> what php file should I need to update.

You should be able to find it with a code search. `Ctrl+Shift+F` if you're using VSCode.

**Comment by AliasGon-1Q** [comment]
Confirming that this suggestion fixes the problem. you can find the file to be edited at your "public_html/wp-content/themes/gwt610/inc/function-options.php" open it though your cPanel, it was on line 76 for me, just declare the function as a static. of just insert "static" without the quotes, between public and function.

**Comment by matchathink** [comment]
> Confirming that this suggestion fixes the problem. you can find the file to be edited at your "public_html/wp-content/themes/gwt610/inc/function-options.php" open it though your cPanel, it was on line 76 for me, just declare the function as a static. of just insert "static" without the quotes, between public and function.

Hello sir.
"public_html/wp-content/themes/gwt610/inc/function-options.php

gwt610 is not listed although I found the function, still the problems persists

**Comment by AliasGon-1Q** [comment]
> > Confirming that this suggestion fixes the problem. you can find the file to be edited at your "public_html/wp-content/themes/gwt610/inc/function-options.php" open it though your cPanel, it was on line 76 for me, just declare the function as a static. of just insert "static" without the quotes, between public and function.
> 
> Hello sir. "public_html/wp-content/themes/gwt610/inc/function-options.php
> 
> gwt610 is not listed although I found the function, still the problems persists

the gwt610 is part of my installation directory, your may be different. but you may search using the CPANEL, gwt610 is the name of the gwt version.

**Comment by matchathink** [comment]
Yup. I was editing the 25.3.3 version. it is ok now, a lifesaver. Hope this will be fixed in the next updates. Thanks

**Comment by JetherPS** [comment]
![image](https://github.com/iGovPhil/gwt-wordpress/assets/174141237/3bbca597-5514-4462-a5a3-cced1f7c84ed)
hi,, where to put static here??

**Comment by JetherPS** [comment]
> Confirming that this suggestion fixes the problem. you can find the file to be edited at your "public_html/wp-content/themes/gwt610/inc/function-options.php" open it though your cPanel, it was on line 76 for me, just declare the function as a static. of just insert "static" without the quotes, between public and function.

where specifically to put static?
![image](https://github.com/iGovPhil/gwt-wordpress/assets/174141237/b0a71f52-3c9a-41a0-974e-81c440d1e85c)

**Comment by AliasGon-1Q** [comment]
> > Confirming that this suggestion fixes the problem. you can find the file to be edited at your "public_html/wp-content/themes/gwt610/inc/function-options.php" open it though your cPanel, it was on line 76 for me, just declare the function as a static. of just insert "static" without the quotes, between public and function.
> 
> where specifically to put static? ![image](https://private-user-images.githubusercontent.com/174141237/344890258-b0a71f52-3c9a-41a0-974e-81c440d1e85c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDU4MDAsIm5iZiI6MTcxOTkwNTUwMCwicGF0aCI6Ii8xNzQxNDEyMzcvMzQ0ODkwMjU4LWIwYTcxZjUyLTNjOWEtNDFhMC05NzRlLTgxYzQ0MGQxZTg1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNzMxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzZhMWI3ZDlmMmY1NjZmOTAwYzM1OWEzOTEwODZlODIxMDk3MjA0YTI0YWVmYWYxOWNmZDRjZTMwZTE1MzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YLxRg6f2dpeqjbT8flCo0CgVGR1PUj7dj9LOl_4KhdY)

Open the file named functions-option.php not the one that you opened.

**Comment by JetherPS** [comment]
> Open the file named functions-option.php not the one that you opened.

okay na po. sa installer pala ung file naiedit sige pa ako hanap sa installed files. salmat
